server:
  port: 8081                 #端口号
  servlet:
    context-path: /          #项目名

spring:
  #  profiles:
  #    active: local          #使用哪个配置文件

  devtools:
    restart:
      enabled: false       #热部署

  thymeleaf:
    cache: false           # 是否启用模板缓存
    encoding: UTF-8        # 编码格式,默认UTF-8
    mode: HTML             # 应用于模板的模板模式
    prefix: classpath:/templates/  # 模板文件存放位置,默认 classpath:/templates/
    suffix: .html          # 后缀默认 .html
    servlet:
      content-type: text/html   # 不配置子文件夹有问题

  servlet:
    multipart:                  #上传文件配置
      enabled: true             #是否支持多文件上传
      max-file-size: 100MB      #最大文件大小
      max-request-size: 100MB   #最大请求大小(多文件上传总大小限制)

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:                          #springboot2不支持配置继承,如多数据源每个要写完整配置
      url: jdbc:mysql://localhost:3306/pts_res?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true          #数据库连接url,必须要加useAffectedRows=true,否则权限判断会有问题
      username: root                            #数据库用户名
      password: root                      #数据库密码
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: mergeStat,config,wall,stat # wall:批量执行多条sql语句，不能注入wall过滤器
      max-active: 20                 # 最大连接池数量
      initial-size: 1                # 初始化时建立物理连接的个数
      max-wait: 3000                 # 获取连接时最大等待时间,单位毫秒
      min-idle: 1                    # 最小连接池数量
      time-between-eviction-runs-millis: 60000   # 有两个含义:1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据,详细看testWhileIdle属性的说明
      min-evictable-idle-time-millis: 300000     # Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于minEvictableIdleTimeMillis,则关闭当前连接
      validation-query: select 1     # 用来检测连接是否有效的sql
      test-while-idle: true           # 建议配置为true,不影响性能,并且保证安全性,申请连接的时候检测,如果空闲时间大于timeBetweenEvictionRunsMillis,执行validationQuery检测连接是否有效
      test-on-borrow: false           # 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能
      test-on-return: false           # 归还连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能




  #缓存方式配置
  #redis缓存
  #######################################################################
  redis:
    database: 0 # Redis数据库索引（默认为0）
    timeout: 10000 #设置客户端超时时间，单位是毫秒，默认为2000
    password: root #密码
    #单机版
    host: 127.0.0.1
    port: 6379
    #集群版
    #    cluster:
    #      max-redirects: 3  # 获取失败 最大重定向次数
    #      nodes:
    #        - 127.0.0.1:6379
    #        - 192.168.91.5:9002
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #最大空闲数
        min-idle: 0 #最小空闲数
      shutdown-timeout: 1000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.neo.model




logging:
  config: classpath:log4j2.xml      #log4j2配置文件名称

#actuator,spring监控服务
management:
  endpoint:
    health:
      show-details: always   #显示健康具体信息  默认不会显示详细信息
  endpoints:
    web:
      base-path: /actuator   #修改访问路径
      exposure:
        include: "*"           #开放所有页面节点  默认只开启了health、info两个节点

#httpclient相关优化配置
http:
  maxTotal: 400                      #设置最大连接数
  defaultMaxPerRoute: 400            #设置每个主机地址的并发数
  connectTimeout: 2000               #创建连接的最长时间
  connectionRequestTimeout: 2000     #从连接池中获取到连接的最长时间
  socketTimeout: 500000               #数据传输的最长时间（毫秒）
  maxIdleTime: 60000                 #空闲时间(用于定期清理空闲连接)



#################自定义配置#################
pts:
  uaa_logout_url: http://auth.yozodocs.com/api/account/logout
  uaa_userinfo_url: http://auth.yozodocs.com/api/account/userinfo

  fcs_upload_url: https://pdl.yozodocs.com/file/upload
  fcs_convert_url: https://pdl.yozodocs.com/composite/convert
  fcs_vToken_url: https://pdl.yozodocs.com/view/vToken
  fcs_downLoad_url: https://pdl.yozodocs.com/view/download
  fcs_http_download_url: https://pdl.yozodocs.com/file/http

  features_version: 0.0.2
  product_hmac_key: qaxet9223210^*&     #密钥
  features_insert_url: http://172.18.21.23/product/api/product/profile/insert     #特性注册地址

  domain: http://192.168.61.122:8081
  feedback_url : http://172.18.21.23/api/ask/commit 	#反馈系统
  
  membership_url: http://172.18.21.23/membership/api/member/event/add    #积分成长
  member_hamc_key: qaxet9223210^*&

  fcs_srcfile_dir: E:\dcs\input                    #fcs文件根目录
  fcs_targetfile_dir: E:\dcs\output      #fcs生产文件目录
  convert_fail_dir:                     #转换失败源文件夹
  report_error_dir:                     #报错文件夹

  yzcloud_domain: http://www.yozodocs.com       #优云域名
  retryFlag: true #是否进行重试